[build]
  publish = "." # Changed from "dist" to "." to publish from the root directory
  functions = "netlify/functions" # This tells Netlify where to find your serverless functions

[functions]
  node_bundler = "esbuild" # Recommended for faster builds
